### ISSUE TITLE
Game crash on launch. 1.20.4

### ISSUE THREAD

**Issue by m-sarabi** [Supchik22/AwesomeFarmer#1]
Thanks for the very helpful mod.
I just downloaded the mod for version 1.20.4, and mod version `1.0.0` and the game crashed on launch.
Here is the crash report *(sorry for it is too long)*:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-04-02 17:29:15
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'awesomefarmer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: field_10168
	at com.supchikwork.AwesomeFarmerClient.<clinit>(AwesomeFarmerClient.java:28)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24020.7 (f5b7a53876c03330b0e7c1a6020590269cbbc2b6):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna7796470327570491070.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 421576352 bytes (402 MiB) / 838860800 bytes (800 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.39
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4624
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 17321.84
	Virtual memory used (MB): 9191.56
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 77.71
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20.4-fabric0.91.2-1.4
		architectury: Architectury 11.1.17
		autofish: XPlus Autofish 1.0.0-fabric-1.20.4
		awesomefarmer: AwesomeFarmer 1.0.0
		badoptimizations: BadOptimizations 2.1.0
		bettermounthud: Better Mount HUD 1.2.2
		carpet: Carpet Mod 1.4.128+v231205
		carpetskyadditions: Carpet Sky Additions Revised 1.20.4-4.4.2
		centered-crosshair: Centered Crosshair 1.0.6
		chatonlostfocus: ChatOnLostFocus 1.2.3
		citresewn: CIT Resewn 1.1.4+1.20.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.4+1.20.4
		clientcommands: Client Commands 2.8.11
			betterconfig: BetterConfig 1.2.1
			clientarguments: clientarguments 1.7
			net_fabricmc_mapping-io: mapping-io 0.5.1
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		completionistsindex: Completionist's Index 20.4.1
		csearcher: ContainerSearcher 0.3.0+mc1.20.4
		disablefrontperspective: disablefrontperspective 1.0.0-fabric+0.91.1+1.20.4
		enhancedblockentities: Enhanced Block Entities 0.9.1+1.20.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0
			spruceui: SpruceUI 5.0.3+1.20.2
		entityculling: EntityCulling 1.6.4
		exordium: Exordium 1.2.1
		extremesoundmuffler: Extreme sound muffler 3.45.1
			fiber: fiber 0.23.0-2
		fabric-api: Fabric API 0.95.4+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.48+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.12+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.2+25e1b4764f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.73+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.31+eabbae364f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.62+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.52+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.33+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.55+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.1.0+0d29db764f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.9+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		fadeless: Fadeless 1.0.1
		ferritecore: FerriteCore 6.0.3
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		immediatelyfast: ImmediatelyFast 1.2.11+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemswapper: ItemSwapper 0.5.6
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.24
			journeymap-api-fabric: JourneyMap API 1.20.2-1.9-fabric-SNAPSHOT
		krypton: Krypton 0.2.6
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		libipn: libIPN 4.0.2
		librarian-trade-finder: Librarian Trade Finder 2.1.1
		litematica: Litematica 0.17.2
		litemoretica: litemoretica 1.2.5+mc1.20.4
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.1
		memoryleakfix: Memory Leak Fix 1.1.5
		meteor-client: Meteor Client 0.5.6-2044
		minecraft: Minecraft 1.20.4
		minihud: MiniHUD 0.30.2
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 9.0.0
		moreculling: More Culling 1.20.4-0.22.1
			conditional-mixin: conditional mixin 0.3.2
			mixinsquared: MixinSquared 0.1.1
		moremcmeta: MoreMcmeta 1.20.4-4.4.7
			moremcmeta_animation_plugin: MoreMcmeta Animation Plugin 1.20.1-1.0.3
			moremcmeta_gui_plugin: MoreMcmeta GUI Plugin 1.20.1-1.0.1
			moremcmeta_json_parser_plugin: MoreMcmeta JSON Parser Plugin 1.20.1-1.1.1
			moremcmeta_properties_parser_plugin: MoreMcmeta Properties Parser Plugin 1.20.1-1.1.5
			moremcmeta_texture_plugin: MoreMcmeta Texture Plugin 1.20.1-1.0.1
		moremcmeta_emissive_plugin: MoreMcmeta Emissive Textures Plugin 1.20.4-2.0.4
		nbt_ac: NBT Autocomplete 1.2
		noglow: noglow 1.1
		notes: Notes 1.20.4-2.1.0-fabric
		owo: oωo 0.12.5+1.20.3
			blue_endless_jankson: jankson 1.2.2
		puzzleslib: Puzzles Lib 20.4.31
		quickmenu: Quick Menu 1.2.3
		raised: Raised 3.1.3
		realmsfix: Realms Button Remover 2.0.3
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		replaymod: Replay Mod 1.20.4-2.6.15
		roughlyenoughitems: Roughly Enough Items 14.0.688
			error_notifier: Error Notifier 1.0.9
		rrls: Remove Reloading Screen 4.0.2+mc1.20.4-fabric
		seedcrackerx: SeedCrackerX 2.14.6
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		status-effect-bars: Status Effect Bars 1.0.4
		titlefixer: Title Fixer 1.0+1.20.4
		tweakeroo: Tweakeroo 0.19.2
		visiblebarriers: Visible Barriers 2.0.11
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: fabric-loader-0.15.6-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>

-- Meteor Client --

Version: 0.5.6
Dev Build: 2044
```

**Comment by Magnogen** [comment]
im having the same problem, so bump!

**Comment by Supchik22** [comment]
Sorry, I'll try to rebuild the mod! I'll fix it soon!

**Comment by Supchik22** [comment]
i fixed it!
